language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - php ./vendor/bin/phpunit -c phpunit.sample.xml

matrix:
  allow_failures:
    - php: 7
